name: TWRP Device Tree Generator ()

on:
  workflow_dispatch:
    inputs:
      IMG_LINK:
        description: 'boot.img ya da recovery.img dosya linki (örnek: https://gofile.io/d/...)'
        required: true
        default: 'https://gofile.io/d/fa9c778c-91cd-4223-8a33-8972635368bd'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repo dosyalarını klonla
        uses: actions/checkout@v3

      - name: Python 3 kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: twrpdtgen scriptini klonla
        run: git clone https://github.com/twrpdtgen/twrpdtgen.git

      - name: Bağımlılıkları yükle (requirements.txt yok)
        run: pip install ./twrpdtgen

      - name: Gerçek download linkini çöz ve boot.img olarak indir
        run: |
          echo "GoFile linki: ${{ github.event.inputs.IMG_LINK }}"
          wget -qO- "${{ github.event.inputs.IMG_LINK }}" | grep -oP '"directLink":"\K[^"]+' | sed 's/\\//g' > link.txt
          curl -L "$(cat link.txt)" -o boot.img

      - name: TWRP tree oluştur
        run: |
          mkdir output
          python3 twrpdtgen/twrpdtgen.py boot.img --output output

      - name: Sonucu artifacts olarak yükle
        uses: actions/upload-artifact@v4
        with:
          name: twrp-tree
          path: output/
