name: TWRP Device Tree Generator (with Link Input)

on:
  workflow_dispatch:
    inputs:
      IMG_LINK:
        description: 'boot.img veya recovery.img dosyası linki'
        required: true
        default: ''
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repo dosyalarını klonla
        uses: actions/checkout@v3

      - name: Python 3 kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: twrpdtgen scriptini klonla
        run: git clone https://github.com/twrpdtgen/twrpdtgen.git

      - name: Gereken modülleri yükle
        run: |
          pip install -r twrpdtgen/requirements.txt

      - name: IMG dosyasını indir (boot.img olarak kaydedilecek)
        run: wget -O boot.img "${{ github.event.inputs.IMG_LINK }}"

      - name: TWRP tree üret
        run: |
          mkdir output
          python3 twrpdtgen/twrpdtgen.py boot.img --output output

      - name: Sonucu artifacts olarak yükle
        uses: actions/upload-artifact@v4
        with:
          name: twrp-tree
          path: output/
