name: TWRP Device Tree Generator ALT

on:
  workflow_dispatch:
    inputs:
      IMG_LINK:
        description: 'boot.img veya recovery.img direkt dosya linki (örnek: https://filebin.net/.../recovery.img)'
        required: true
        default: 'https://filebin.net/goazefd6h87gmzbp/recovery.img'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repo dosyalarını klonla
        uses: actions/checkout@v3

      - name: Python 3 kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: twrpdtgen scriptini klonla
