name: TWRP Device Tree Generator Alternative

on:
  workflow_dispatch:
    inputs:
      IMG_LINK:
        description: 'boot.img veya recovery.img dosya linki'
        required: true
        default: 'https://filebin.net/goazefd6h87gmzbp/recovery.img'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repo dosyalarını klonla
        uses: actions/checkout@v3

      - name: Python 3 kurulumu
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: twrpdtgen scriptini klonla
        run: git clone https://github.com/twrpdtgen/twrpdtgen.git

      - name: twrpdtgen klasörüne geç
        run: cd twrpdtgen && pip install .

      - name: recovery.img dosyasını indir (boot.img adıyla)
        run: wget -O boot.img "${{ github.event.inputs.IMG_LINK }}"

      - name: TWRP tree oluştur
        run: |
          mkdir output
          python3 -m twrpdtgen boot.img --output output

      - name: Tree'yi artifacts olarak yükle
        uses: actions/upload-artifact@v4
        with:
          name: twrp-tree
          path: output/
